### ISSUE TITLE
Finalize Command Line Agruments

### ISSUE THREAD

**Issue by marissaodonnell** [BlueAcornInc/dockmaster#1] opened 2016-12-05 16:51 UTC

**Comment by briceburg** [comment] 2016-12-06 16:58
@SamTay can you send in proposal for commands and their args here? This is a duplicate of https://github.com/dockerland/dockmaster/issues/3

**Comment by SamTay** [comment] 2016-12-06 17:28
### `dm` usage proposal:
`dm` really only has two defined options
- `--help` flag to output help information
- `--composition` option accepts a path argument to composition directory. defaults to CWD

The rest of the arguments to DM are parsed through the resolved `dockmaster.yml` file and forwarded to docker-compose. This is best explained by the help output below (taken from the current [haskell version](https://github.com/samtay/dockmaster)):
```shell
dm - yaml loving docker compose orchestration

Usage: dm [-c|--composition PATH] COMMAND [args]
  Orchestrate your docker-compose

Available options:
  -h,--help                Show this help text
  -c,--composition PATH    Composition directory. Note this can be relative to
                           DM_COMPOSITIONS_DIR array. (default: ".")
```
where `COMMAND` can be any string, but will usually correspond to a `docker-compose` command such as `up`,`down`, etc, and `[args]` are the optional arguments/options that follow that command. For example the corresponding dockmaster orchestration of
```shell
cd compositions/deploybot
docker-compose logs --follow deploybot_container
```
is
```shell
dm -c deploybot -- logs --follow deploybot_container
# COMMAND == "logs"
# [args] == "--follow deploybot_container"
```

We keep the `COMMAND` argument on its own, separate from `[args]` because it is used an identifier in certain `dockmaster.yml` directives. I also advocate it should be required for `dm` to run... if someone wants to run `docker-compose` for its own help output, they should do that outside of `dm`.

**Comment by SamTay** [comment] 2016-12-06 17:37
### `dmc` usage proposal
`dmc` is very simple. It accepts an option and an optional value, similar to git config:
```
dmc - dockmaster configuration

Usage: dmc OPTION [VALUE]

Available options:
  -h,--help                Show this help text
```
If no value is supplied, this prints the current OPTION value to stdout. If a value is supplied, it is sets the OPTION to said value. The option=value settings are stored and retrieved from `~/.dockmaster/config` or something like that (suggestions?).

#### caveats
Perhaps we need a specific `dmc` option for adding a directory to the compositions dir? Otherwise....
```shell
dmc DOCKMASTER_COMPOSITION_PATH "$(dmc DOCKMASTER_COMPOSITION_PATH):/new/composition/listing"
# yikes
```

Also @briceburg how do you think we should store the path listings? Array? Colon separated list like above? Space separated list?

**Comment by briceburg** [comment] 2016-12-06 18:56
@SamTay looks good. I think `dm` is nailed.  

For `dmc` I think we can get by with what you have but it's not future proof. E.g. it's more-or-less always limited to setting an option. Lets future proof it by adding commands? E.g.

```
dmc set COMPOSITION_PATH $(dmc get COMPOSITION_PATH):/new/compositions-dir
```

though the current simplicity is pretty damn good.

I think colon separated works because it's bash readable and conventional (e.g. PATH). Otherwise we ought to use yaml configuration.

We may eventually want to store hook presets/plugins. E.g. the ability to re-use a hook that suggests a network segment to tag a composition with. We can to this through `dockmaster.yml` and absolute paths, but ought to think about DOCKMASTER_HOME variable -- such as

```
~/.dockmaster/plugins/
~/.dockemaster/compositions/

/etc/dockmaster/plugins/
/etc/dockmaster/compositions/
```

etc.

**Comment by SamTay** [comment] 2016-12-06 23:53
Do you have a preference on what config file should look like, and exactly where it should be? I like the idea of yaml (`~/.dockmaster/config.yml`), only then we need to invest more time in `dmc` because setting/getting functionality will be more complicated than a simple flat file of `option=value` lines.. should we maybe start with the latter for MVP ??

Or, MVP can still be yaml but we only support depth of level 1 for now, like
```yml
COMPOSITION_PATH: /one/dir:/two/dir:/three/dir
SOMETHING_ELSE: "blah"
```

Idk. I never was good at KISS. Let me know your thoughts.

**Comment by briceburg** [comment] 2016-12-07 00:11
@SamTay 

I would try DOCKMASTER_CONFIG before ~/.dockmaster/config.yml before falling back to /etc/dockmaster/config.yml

e.g.

```sh
# in order of precedence
DOCKMASTER_CONFIG=/some/path/to/dockmaster.yml dm -c hubot start
dm -c hubot start
# ^^^ tries ~/.dockmaster/config.yml, then /etc/dockmaster/config.yml
```

I actually planned to use an ini format for the config instead of yaml in my first attempt -- mainly to differentiate it from the dockmaster.yml composition file. Although this could be a bit awkward -- esp. when not using COP.

Here's the script as it stands;
https://github.com/dockerland/dockmaster/blob/briceburg-bash-poc/lib.d/config.sh#L21

so the .cfg file looks like

```ini
; compostion paths
paths[] = ~/.dockmaster/compositions
paths[] = /etc/dockmaster/compositions
```

although I like either keeping this as a shell vars file (flat, with colon separated paths for the DOCKMASTER_COMPOSTION_PATHS var). If you do use yaml, express as an array. Having the colon trailing COMPOSTION_PATH`:`  will fuck shit up. 

```yml
PATHS:
  - /one/dir
  - /two/dir
  - /three/dir
```

**Comment by briceburg** [comment] 2016-12-07 00:18
I should also note that we should respect the DOCKMASTER_COMPOSTION var if the `-c` flag to `dm` doesn't get passed.

e.g.
```sh
DOCKMASTER_COMPOSTION=hubot dm start
```

and as per usual, flags will override the variable. e.g.

```sh
DOCKMASTER_COMPOSTION=hubot dm -c slackerbot start
# ^^^ starts the slackerbot
```

this is the pattern we use in bash

```sh
local composition=${DOCKMASTER_COMPOSITION:-.}

# argparsing later... if -c is encountered,
composition="$2" ; shift ;;
```

e.g. see:
[help] https://github.com/BlueAcornInc/devops-prototype-skel/blob/briceburg/fs1/common/bin/mkdocker#L30
[implementation] https://github.com/BlueAcornInc/devops-prototype-skel/blob/briceburg/fs1/common/bin/mkdocker#L63
[flag overrride] https://github.com/BlueAcornInc/devops-prototype-skel/blob/briceburg/fs1/common/bin/mkdocker#L75

**Comment by SamTay** [comment] 2016-12-08 03:12
Ok. I understand. Just implemented your note on DOCKMASTER_COMPOSTION envvar today. Also implemented the location fallback structure you mentioned above for the global config.yml. Right now, its implemented as config.yml and just supports the one PATHS array:
```yml
PATHS:
  - /path1
  - /path2
```

I'm gonna keep moving forward with `dm` for now, then move onto `dmc`. However, one of the reasons I was hesitant to go straight to config.yml PATHS array was the complication for `dmc`. How would you like me to handle adding/removing paths? Should we just have direct commands for that node, e.g.
```shell
dmc addpath /path1
dmc addpath /path2
dmc removepath /path1

## or generalized "add/remove" commands for modifying top level arrays
dmc add PATHS /path1
dmc add PATHS /path2
dmc add PATHS /path3
dmc remove PATHS /path1
dmc add ARRAYOPTION onevalue

## and "set/get" would be for flat values at top level
dmc set ARBITRARY BLAH
``` 
resulting in
```yml
PATHS:
  - /path2
  - /path3
ARRAYOPTION:
  - onevalue
ARBITRARY: BLAH
```

Not trying to go crazy here, smelling like jq...

**Closed** 2016-12-19 21:04 UTC
